version: '3'

services:

  backend:
    container_name: 'chat-backend' #容器名称
    build: ./service
    restart: always
    environment:
      OPENAI_API_KEY: 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
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL: https://api.acfun.wiki
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 100000
    ports:
      - "3002:3002"

  frontend:
    container_name: 'chat-frontend' #容器名称
    image: nginx  #指定镜像
    # build: ./frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf #挂载nginx配置
      - ./dist:/usr/src/app/
    depends_on:
      - backend
